import React,{useState}from'react';
import{Save,Sparkles,Loader2}from'lucide-react';
import{Button}from'@/components/ui/button';
import{useApp}from'@/context/AppContext';
import{supabase}from'@/integrations/supabase/client';
import{toast}from'sonner';

type TipoAtivo='veiculo'|'equipamento';
type FormState={tipo:TipoAtivo;descricao:string;placa:string;patrimonio:string;renavam:string;chassi:string;ano_fabricacao:string;ano_modelo:string;empresa:string;marca:string;modelo:string;observacao:string};
const EMPTY:FormState={tipo:'veiculo',descricao:'',placa:'',patrimonio:'',renavam:'',chassi:'',ano_fabricacao:'',ano_modelo:'',empresa:'TOPAC MATRIZ',marca:'',modelo:'',observacao:''};
const plain=(v:unknown)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim();
const plate=(v:unknown)=>plain(v).replace(/[^A-Z0-9]/g,'').match(/[A-Z]{3}[0-9][A-Z0-9][0-9]{2}/)?.[0]||'';
const renavam=(v:unknown)=>String(v||'').replace(/\D/g,'').match(/\d{9,11}/)?.[0]||'';
const chassis=(v:unknown)=>plain(v).replace(/[^A-Z0-9]/g,'').match(/[A-HJ-NPR-Z0-9]{17}/)?.[0]||'';
const year=(v:unknown)=>String(v||'').match(/(?:19|20)\d{2}/)?.[0]||'';
const patrimonio=(v:unknown)=>plain(v).match(/\b[A-Z]\d{1,3}\.\d{1,5}\b/)?.[0]||'';
const first=(...v:unknown[])=>v.map(x=>String(x||'').trim()).find(Boolean)||'';
const parseLocal=(text:string)=>{const n=plain(text);const equipment=/\b(COMPRESSOR|GERADOR|EQUIPAMENTO|PLATAFORMA|BOMBA|TORRE DE ILUMINACAO|MOTOCOMPRESSOR)\b/.test(n);const years=n.match(/\b((?:19|20)\d{2})\s*\/\s*((?:19|20)\d{2})\b/);const model=first(n.match(/\bMARCA\s*\/?\s*MODELO\b\s*[:\-]?\s*([A-Z0-9][A-Z0-9 .\/-]{1,70}?)(?=\s+\b(?:PLACA|RENAVAM|CHASSI|ANO|COR|PATRIMONIO)\b|$)/i)?.[1],n.match(/\bMODELO\b\s*[:\-]?\s*([A-Z0-9][A-Z0-9 .\/-]{1,70}?)(?=\s+\b(?:PLACA|RENAVAM|CHASSI|ANO|COR|PATRIMONIO)\b|$)/i)?.[1]);return{tipo:(equipment?'equipamento':'veiculo')as TipoAtivo,descricao:model?`${equipment?'EQUIPAMENTO':'CARRO'} - ${model}`:equipment?'EQUIPAMENTO':'',placa:plate(n.match(/\bPLACA\b[^A-Z0-9]{0,20}([A-Z]{3}\s*-?\s*[0-9][A-Z0-9]\s*-?\s*[0-9]{2})/i)?.[1]||n),patrimonio:patrimonio(n),renavam:renavam(n.match(/\bRENAVAM\b[^0-9]{0,30}(\d[\d.\s-]{7,16})/i)?.[1]||''),chassi:chassis(n.match(/\b(?:CHASSI|VIN)\b[^A-Z0-9]{0,30}([A-HJ-NPR-Z0-9]{17})/i)?.[1]||''),ano_fabricacao:years?.[1]||'',ano_modelo:years?.[2]||years?.[1]||'',modelo:model};};
export default function FrotaCadastroInteligente({onSaved}:{onSaved:()=>void|Promise<void>}){const{session}=useApp();const[form,setForm]=useState<FormState>(EMPTY);const[smartText,setSmartText]=useState('');const[parsing,setParsing]=useState(false);const[saving,setSaving]=useState(false);const[ready,setReady]=useState(false);
const process=async()=>{if(!smartText.trim())return toast.error('Cole os dados do documento antes de processar.');setParsing(true);try{const local=parseLocal(smartText);let ai:Record<string,unknown>={};try{const{data,error}=await supabase.functions.invoke('parse-text',{body:{type:'documento_veiculo',text:smartText.slice(0,60000)}});if(!error)ai=(data?.data||{})as Record<string,unknown>;}catch{}const context=plain(`${smartText} ${ai.descricao||''} ${ai.tipo_veiculo||''}`);const tipo:TipoAtivo=/\b(COMPRESSOR|GERADOR|EQUIPAMENTO|PLATAFORMA|BOMBA|TORRE|MOTOCOMPRESSOR)\b/.test(context)||ai.tipo==='equipamento'||local.tipo==='equipamento'?'equipamento':'veiculo';const modelo=first(ai.modelo,ai.marca_modelo,local.modelo);setForm({...EMPTY,tipo,descricao:first(ai.descricao,local.descricao,modelo?`${tipo==='equipamento'?'EQUIPAMENTO':'CARRO'} - ${modelo}`:''),placa:plate(first(local.placa,ai.placa)),patrimonio:first(local.patrimonio,ai.patrimonio),renavam:renavam(first(local.renavam,ai.renavam)),chassi:chassis(first(local.chassi,ai.chassi)),ano_fabricacao:year(first(local.ano_fabricacao,ai.ano_fabricacao,ai.ano)),ano_modelo:year(first(local.ano_modelo,ai.ano_modelo,ai.ano)),empresa:first(ai.empresa,'TOPAC MATRIZ'),marca:first(ai.marca),modelo,observacao:first(ai.observacao)});setReady(true);toast.success('Dados interpretados: placa, RENAVAM e chassi conferidos quando presentes.');}catch(e:any){toast.error(e?.message||'Não foi possível interpretar os dados.');}finally{setParsing(false);}};
const save=async()=>{if(!session?.user?.id)return toast.error('Sessão expirada.');if(!ready)return toast.error('Interprete os dados primeiro.');setSaving(true);try{const payload={user_id:session.user.id,tipo:form.tipo,descricao:form.descricao||'CARRO',placa:form.placa,patrimonio:form.patrimonio,renavam:form.renavam,chassi:form.chassi,ano_fabricacao:form.ano_fabricacao,ano_modelo:form.ano_modelo,empresa:form.empresa,marca:form.marca,modelo:form.modelo,tipo_veiculo:form.tipo==='equipamento'?'equipamento':'carro',observacao:form.observacao,status:'ativo',updated_at:new Date().toISOString()};let id='';if(form.placa){const{data}=await supabase.from('ativos').select('id').eq('placa',form.placa).limit(1).maybeSingle();id=data?.id||'';}if(id){const{error}=await supabase.from('ativos').update(payload as any).eq('id',id);if(error)throw error;}else{const{error}=await supabase.from('ativos').insert(payload as any);if(error)throw error;}toast.success(id?'Veículo atualizado. Documento anterior permanece preservado.':'Veículo cadastrado.');setForm(EMPTY);setSmartText('');setReady(false);await onSaved();}catch(e:any){toast.error(e?.message||'Erro ao salvar.');}finally{setSaving(false);}};
return <section className="card-premium p-5 space-y-5 border-l-4 border-primary"><div><h2 className="text-lg font-bold">Janela Inteligente da Frota</h2><p className="text-xs text-muted-foreground">Cole os dados do documento. Não há mais preenchimento tradicional. O sistema identifica placa, RENAVAM, chassi, ano e veículo.</p></div><textarea value={smartText} onChange={e=>{setSmartText(e.target.value);setReady(false)}} rows={8} placeholder="Cole aqui o texto ou os dados extraídos do documento..." className="w-full resize-y rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"/><Button onClick={()=>void process()} disabled={parsing||!smartText.trim()} variant="outline" className="w-full">{parsing?<Loader2 className="w-4 h-4 mr-2 animate-spin"/>:<Sparkles className="w-4 h-4 mr-2"/>}{parsing?'Interpretando...':'Interpretar documento'}</Button>{ready&&<div className="rounded-xl border border-primary/30 bg-primary/5 p-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm"><div><b>Placa</b><div>{form.placa||'—'}</div></div><div><b>RENAVAM</b><div>{form.renavam||'—'}</div></div><div><b>Chassi</b><div className="break-all">{form.chassi||'—'}</div></div><div><b>Ano</b><div>{form.ano_fabricacao||'—'} / {form.ano_modelo||'—'}</div></div><div className="col-span-2"><b>Veículo</b><div>{form.descricao||form.modelo||'—'}</div></div><div><b>Empresa</b><div>{form.empresa}</div></div><div><b>Patrimônio</b><div>{form.patrimonio||'—'}</div></div></div><Button onClick={()=>void save()} disabled={saving} className="mt-4 w-full">{saving?<Loader2 className="w-4 h-4 mr-2 animate-spin"/>:<Save className="w-4 h-4 mr-2"/>}{saving?'Salvando...':'Confirmar e salvar'}</Button></div>}</section>;
}