import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Boxes,ClipboardList,FileText,History,Loader2,Package,Plus,Search,ShoppingCart,Upload}from'lucide-react';
import{toast}from'sonner';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{Textarea}from'@/components/ui/textarea';
import{supabase}from'@/integrations/supabase/client';
import{useApp}from'@/context/AppContext';
const db=supabase as any;
const START='2026-09-16';
const today=()=>new Date().toISOString().slice(0,10);
const br=(v:any)=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
type Mode='home'|'entrada'|'retirada'|'estoque'|'dia'|'relatorios'|'historico';
type Cart={item_id:string;quantidade:number;nome:string;codigo:string};
const AlmoxarifadoDesktopV4:React.FC=()=>{
 const{session,employees,companies}=useApp();const[mode,setMode]=useState<Mode>('home');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[stock,setStock]=useState<any[]>([]);const[entries,setEntries]=useState<any[]>([]);const[loads,setLoads]=useState<any[]>([]);const[search,setSearch]=useState('');const[personId,setPersonId]=useState('');const[itemId,setItemId]=useState('');const[qty,setQty]=useState('1');const[cart,setCart]=useState<Cart[]>([]);const[note,setNote]=useState('');const[smart,setSmart]=useState('');const[entItem,setEntItem]=useState('');const[entQty,setEntQty]=useState('');const[entSupplier,setEntSupplier]=useState('');const[entNf,setEntNf]=useState('');const[entValue,setEntValue]=useState('');const[entFile,setEntFile]=useState<File|null>(null);const[from,setFrom]=useState(START);const[to,setTo]=useState(today());
 const company=(e:any)=>companies.find((c:any)=>c.id===(e.companyId||e.company_id||e.empresa_id));const name=(e:any)=>e.name||e.nome||'';
 const people=useMemo(()=>employees.filter((e:any)=>e.status==='ativo'||e.ativo===true).filter((e:any)=>{const n=name(e).toUpperCase();const c=String(company(e)?.name||company(e)?.nome||'').toUpperCase();if(n.includes('ANTÔNIO CARLOS')||n.includes('ANTONIO CARLOS')||n.includes('EDENILSON VICTOR'))return true;return !c.includes('GOIÂNIA')&&!c.includes('GOIANIA')&&!c.includes('GOIÁS')&&!c.includes('GOIAS');}).sort((a:any,b:any)=>name(a).localeCompare(name(b),'pt-BR')),[employees,companies]);
 const fetchData=async()=>{setLoading(true);const[s,e,l]=await Promise.all([db.from('almoxarifado_estoque_resumo').select('*').eq('ativo',true),db.from('almoxarifado_entradas').select('*').gte('data_entrada',START).order('data_entrada',{ascending:false}),db.from('almoxarifado_cargas').select('*').gte('created_at',START+'T00:00:00').order('created_at',{ascending:false})]);if(s.error)toast.error(s.error.message);else setStock((s.data||[]).sort((a:any,b:any)=>String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR')));if(!e.error)setEntries(e.data||[]);if(!l.error)setLoads(l.data||[]);setLoading(false)};useEffect(()=>{void fetchData()},[]);
 const itemMap=useMemo(()=>new Map(stock.map((i:any)=>[i.id,i])),[stock]);const filtered=stock.filter((i:any)=>!search||[i.codigo_topac,i.codigo_alternativo,i.nome,i.aplicacao].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())));
 const add=()=>{const i:any=itemMap.get(itemId),q=Number(qty);if(!i||q<=0)return toast.error('Selecione material e quantidade.');if(q>Number(i.saldo||0))return toast.error('Quantidade maior que o saldo.');setCart(v=>{const f=v.find(x=>x.item_id===i.id);return f?v.map(x=>x.item_id===i.id?{...x,quantidade:x.quantidade+q}:x):[...v,{item_id:i.id,quantidade:q,nome:i.nome,codigo:i.codigo_topac}]});setItemId('');setQty('1')};
 const saveWithdrawal=async()=>{if(!personId||!cart.length)return toast.error('Selecione funcionário e materiais.');setBusy(true);try{const obs=[note,smart&&`Registro inteligente: ${smart}`].filter(Boolean).join(' | ');const{data,error}=await db.rpc('almoxarifado_criar_carga_v2',{p_tipo:'retirada',p_funcionario_id:personId,p_veiculo:null,p_placa:null,p_itens:cart.map(x=>({item_id:x.item_id,quantidade:x.quantidade})),p_observacoes:obs||null});if(error)throw error;toast.success(`Retirada ${data?.protocolo||''} registrada e estoque baixado.`);setCart([]);setPersonId('');setNote('');setSmart('');await fetchData();setMode('dia')}catch(e:any){toast.error(e?.message||'Erro ao registrar retirada.')}finally{setBusy(false)}};
 const saveEntry=async()=>{const q=Number(entQty),val=Number(entValue||0);if(!entItem||q<=0)return toast.error('Selecione item e quantidade.');setBusy(true);try{let url='';if(entFile){const path=`almoxarifado/nf/${Date.now()}-${entFile.name}`;const up=await supabase.storage.from('documentos-ativos').upload(path,entFile);if(up.error)throw up.error;url=supabase.storage.from('documentos-ativos').getPublicUrl(path).data.publicUrl}const{error}=await db.from('almoxarifado_entradas').insert({user_id:session?.user?.id,item_id:entItem,quantidade:q,fornecedor:entSupplier||null,valor_unitario:val,valor_total:q*val,nota_fiscal:entNf||null,nota_fiscal_url:url||null,data_entrada:today(),responsavel_nome:session?.user?.email||'Almoxarifado',hora_informada:true});if(error)throw error;toast.success('Entrada registrada e saldo atualizado.');setEntQty('');setEntSupplier('');setEntNf('');setEntValue('');setEntFile(null);await fetchData();setMode('home')}catch(e:any){toast.error(e?.message||'Erro na entrada.')}finally{setBusy(false)}};
 const periodLoads=loads.filter((r:any)=>{const d=String(r.created_at||'').slice(0,10);return d>=from&&d<=to});const dayLoads=loads.filter((r:any)=>String(r.created_at||'').slice(0,10)===today());
 const printPerson=(p:any)=>{const rows=dayLoads.filter((r:any)=>r.funcionario_id===p.id);if(!rows.length)return;const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>Retiradas - ${name(p)}</title><style>body{font-family:Arial;padding:28px}h1{font-size:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}.sign{margin-top:60px;border-top:1px solid #111;padding-top:6px;width:360px}</style></head><body><h1>TOPAC — Relatório diário de retiradas</h1><p><b>Funcionário:</b> ${name(p)}<br/><b>Data:</b> ${br(today())}<br/><b>Operador:</b> ${session?.user?.email||'Almoxarifado'}</p><table><tr><th>Hora</th><th>Protocolo</th><th>Registro</th></tr>${rows.map((r:any)=>`<tr><td>${new Date(r.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td><td>${r.protocolo||'—'}</td><td>${r.observacoes||'Retirada registrada no estoque'}</td></tr>`).join('')}</table><div class='sign'>Assinatura do funcionário</div></body></html>`);w.document.close();w.print()};
 if(loading)return <div className="almox-v3 grid min-h-[480px] place-items-center"><div className="flex gap-2 text-white"><Loader2 className="h-5 w-5 animate-spin"/>Carregando...</div></div>;
 const back=<button className="almox-back" onClick={()=>setMode('home')}><ArrowLeft className="h-4 w-4"/>Voltar ao painel</button>;
 return <div className="almox-v3 p-4 md:p-6">{mode==='home'&&<><div className="mb-6"><h1 className="text-3xl font-black text-white">Almoxarifado</h1><p className="text-slate-300">Operação diária • baixa simultânea • fechamento manual assinado</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[[Plus,'Entrada','Nota fiscal e entrada de materiais','entrada'],[ShoppingCart,'Retirada por funcionário','Única saída operacional; baixa automática','retirada'],[Boxes,'Estoque','Saldo atual e pesquisa','estoque'],[ClipboardList,'Fechamento do dia','Relatórios individuais para assinatura','dia'],[FileText,'Relatórios','Período livre e fechamento mensal','relatorios'],[History,'Histórico','Somente a partir de 16/09/2026','historico']].map(([I,t,s,m]:any)=><button key={m} onClick={()=>setMode(m)} className="almox-hub-card tone-purple"><span className="almox-hub-icon"><I className="h-6 w-6"/></span><div className="almox-hub-title mt-4">{t}</div><div className="almox-hub-subtitle">{s}</div></button>)}</div></>}
 {mode==='retirada'&&<>{back}<h2 className="mb-4 text-2xl font-black text-white">Retirada por funcionário</h2><div className="grid gap-4 xl:grid-cols-[380px_1fr]"><div className="almox-panel p-5"><label className="almox-label">Funcionário</label><select className="almox-control mt-2" value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Selecionar...</option>{people.map((p:any)=><option key={p.id} value={p.id}>{name(p)}</option>)}</select><Textarea className="almox-textarea mt-4" value={smart} onChange={e=>setSmart(e.target.value)} placeholder="Janela inteligente: escreva em linguagem simples o que está sendo entregue..."/><Textarea className="almox-textarea mt-3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Observação opcional"/></div><div className="almox-panel p-5"><div className="grid gap-2 md:grid-cols-[1fr_110px_auto]"><select className="almox-control" value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Material...</option>{stock.map((i:any)=><option key={i.id} value={i.id}>{i.codigo_topac} — {i.nome} — saldo {i.saldo}</option>)}</select><Input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="1"/><Button onClick={add}>Adicionar</Button></div><div className="mt-4 space-y-2">{cart.map(x=><div key={x.item_id} className="flex justify-between rounded-xl border border-slate-700 p-3 text-white"><span>{x.codigo} — {x.nome}</span><b>{x.quantidade}</b></div>)}</div><Button className="mt-5 w-full" disabled={busy} onClick={saveWithdrawal}>{busy?'Registrando...':'Confirmar retirada e baixar estoque'}</Button></div></div></>}
 {mode==='entrada'&&<>{back}<h2 className="mb-4 text-2xl font-black text-white">Entrada de materiais</h2><div className="almox-panel grid gap-3 p-5 md:grid-cols-2"><select className="almox-control md:col-span-2" value={entItem} onChange={e=>setEntItem(e.target.value)}><option value="">Material...</option>{stock.map((i:any)=><option key={i.id} value={i.id}>{i.codigo_topac} — {i.nome}</option>)}</select><Input placeholder="Quantidade" type="number" value={entQty} onChange={e=>setEntQty(e.target.value)}/><Input placeholder="Valor unitário" type="number" value={entValue} onChange={e=>setEntValue(e.target.value)}/><Input placeholder="Fornecedor" value={entSupplier} onChange={e=>setEntSupplier(e.target.value)}/><Input placeholder="Nota fiscal" value={entNf} onChange={e=>setEntNf(e.target.value)}/><Input className="md:col-span-2" type="file" accept="application/pdf,image/*" onChange={e=>setEntFile(e.target.files?.[0]||null)}/><Button className="md:col-span-2" disabled={busy} onClick={saveEntry}>Registrar entrada</Button></div></>}
 {mode==='estoque'&&<>{back}<h2 className="mb-4 text-2xl font-black text-white">Estoque atual</h2><div className="almox-panel p-5"><div className="relative mb-4"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="pl-9" placeholder="Código ou material" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="space-y-2">{filtered.map((i:any)=><div key={i.id} className="flex justify-between rounded-xl border border-slate-700 p-3 text-white"><span><b>{i.codigo_topac}</b> — {i.nome}</span><b>{i.saldo}</b></div>)}</div></div></>}
 {mode==='dia'&&<>{back}<h2 className="mb-1 text-2xl font-black text-white">Fechamento do dia</h2><p className="mb-4 text-slate-300">Imprima um relatório para cada funcionário que retirou material hoje. Assinatura é manual.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{people.filter((p:any)=>dayLoads.some((r:any)=>r.funcionario_id===p.id)).map((p:any)=><button key={p.id} onClick={()=>printPerson(p)} className="almox-panel p-5 text-left text-white"><b>{name(p)}</b><div className="mt-1 text-sm text-slate-300">{dayLoads.filter((r:any)=>r.funcionario_id===p.id).length} registro(s) • imprimir</div></button>)}</div></>}
 {mode==='relatorios'&&<>{back}<h2 className="mb-4 text-2xl font-black text-white">Relatórios</h2><div className="almox-panel p-5"><div className="grid gap-3 md:grid-cols-2"><label className="text-white">De<Input type="date" value={from} min={START} onChange={e=>setFrom(e.target.value)}/></label><label className="text-white">Até<Input type="date" value={to} min={START} onChange={e=>setTo(e.target.value)}/></label></div><div className="mt-5 text-white"><b>{periodLoads.length}</b> protocolos no período. Use 1 dia, 3 dias, 7 dias ou o mês completo alterando as datas.</div></div></>}
 {mode==='historico'&&<>{back}<h2 className="mb-4 text-2xl font-black text-white">Histórico operacional</h2><div className="almox-panel p-5 text-white"><p className="mb-4 text-sm text-slate-300">Registros anteriores a {br(START)} ficam arquivados e não aparecem na operação corrente.</p>{loads.map((r:any)=><div key={r.id} className="border-b border-slate-700 py-3"><b>{r.funcionario_nome||'Funcionário'}</b> • {br(r.created_at)} • {r.protocolo||'—'}</div>)}</div></>}</div>};
export default AlmoxarifadoDesktopV4;
