// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://bywsbeunrmbaqhvzluji.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5d3NiZXVucm1iYXFodnpsdWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MzczNDksImV4cCI6MjA4OTQxMzM0OX0.4t2FHgcrLW1bCUAz0SvqcTbCiWn3KoBnoNhkYtZ75wU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
