import { createHash } from 'node:crypto';
import { PDFDocument } from 'pdf-lib';
import { getServiceClient, sendJson } from '../src/server/payrollServer.js';

const SEED_TOKEN = 'GARAGEM-SEED-2026-09-3e5cb7a1d2';
const COMPETENCIA = '2026-09';
const BUCKET = 'payroll-private';

const PDF_BASE64 =
'JVBERi0xLjMKJeLjz9MKMSAwIG9iago8PAovUHJvZHVjZXIgKHB5cGRmKQo+PgplbmRvYmoKMiAwIG9iago8PAovVHlwZSAvUGFnZXMKL0NvdW50IDYKL0tpZHMgWyA0IDAgUiA5IDAgUiAxNCAwIFIgMTkgMCBSIDI0IDAgUiAyOSAwIFIgXQo+PgplbmRvYmoKMyAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2JqCjQgMCBvYmoKPDwKL0NvbnRlbnRzIDUgMCBSCi9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdCi9SZXNvdXJjZXMgPDwKL0ZvbnQgNiAwIFIKL1Byb2NTZXQgWyAvUERGIC9UZXh0IC9JbWFnZUIgL0ltYWdlQyAvSW1hZ2VJIF0KPj4KL1JvdGF0ZSAwCi9UcmFucyA8PAo+PgovVHlwZSAvUGFnZQovUGFyZW50IDIgMCBSCj4+CmVuZG9iago1IDAgb2JqCjw8Ci9GaWx0ZXIgWyAvQVNDSUk4NURlY29kZSAvRmxhdGVEZWNvZGUgXQovTGVuZ3RoIDEyMTUKPj4Kc3RyZWFtCkdhdG06PkFyZHImOlZzL1IibWw0N3U+b1dmOWMpQExtKDFwMEpzPU48Ri1aTytCS0MpUytLOE1vcG10U1hHUEMvPDFza180YWNrR1wkSWtYSmApO2FoYW4jK05hVktFSk1OJD41WV0uTEJFaXAtO2EiYlk3SjVJI1QkZU5CJj9tMG0zMCZuTTFcZkxpclVFIig/bFhMOWhdVmInVTJNVWxfQHRyNGAhZ0R1YjBscTBvPlUxVS5sKkUpI2ZkaHE2S2pzX2tJOnEmN0BSRkBtMDhoYjpyOD0qYy5pZGpvSSYrLSE3VWNCRj5eYV1wMUE6NF9rUyNvTzhkVVRyNktYJVZYX3M8SzA2a2VfPWdHPUolbnFlTVY3WGtRTFpIMWYtNXReMFonbkFrWk5xbTtPOD4qYVNldCZTQVFOLGBZZltUWDxoXUMsMlVITmVpQDh1SVllUmdWVSQ3ME83dGxjXCIhclJjZEsrSGk/bGwoVldNJzEuKUpLbSpNJj5ISzVIM09lb2RBPTAzRGxUP3MsUUZkVzkqR2VqNmdTbWEuRG5LNUw8JSlSQmghRVI8TjttalRXcUsvMWI4R2krLGFHVzhhTSIzaVdfP0xAblhsTjs2ZztxbXJMKTdZNCpLQ1V1K0JpTF9mZmhiXFojLVU+VmQmI1pwTyMkPFpcUjQxSEFhb1ZxIz44dFYibixYP0JBPkkqcWxsOW9mRkFZSUokXC9mbURKX2pNJjFwR1VOW2UuTVNbMlAxN2BjWVo7XG1YVG9pUEE+VVEkTzZFZ28mYDVEbz9Oay85dVZTZSsuUyFNK1M5JE1IJ0MxIVpxRSoubiJQMVswMW8hWjAjTktVOHIyPlE0N19JMkxybi5hKGtEc2tHWGFmXExBTFV1LVdhajxITj5jSmpoX3JRWGVMTUFkUUcyNyNrPUVvNl1MI10rbz50PmZeXS02c1xtQy91LzNAbFQxVldAVypHYCJhaChCTEVLN1Nxby1RczAiR0EyXiRtRElNLy09cyc3YGVVJGo7aFc0cSFMYXFGKlhRKm5eb2QrRWVLcVNCT0xWTWNrK2gqLHBWZFIqc19cPSQ3VlxFPVw5MltITFghPW0yS3JXPUQ+bixJUk5TZT4ucGMrNlNfWVllVGVeOCg8JTQyb0ZyR15sM0UrN2lMJXUoPDtXcl5tPUMnbWZrT09OSHFBVS11RDEkNDYxN0lqSiNBX1BsZCVlcS1TRGZMP2tMSkU/LmYyTmNoYlJUPVhAdS09Kk1dbEJkMTZRUCciT1YsR20/bT1pSWhfQjxVM0RkaGluKGguXS5jRUYlZiVockZuMVkmLlw8SD4zRkdbQGRGKU8pbi5fXW5cbFVCbEQiOGQuPD9QTnNsdFdyPEtkOk5cI1VCVzJAdUspNTg5JkpycDoyNGImKWE/KGFKSyZFMyxSZDgwUSMoQ0VuIU1vRmxhJTRiPiMjKGRVZTlAKm9EaUkyRCtnMCg7Y0QxS0pUcUJxNmRKYjIvWUFcJ2AxbzVDMmUwLTBsPk4/cV9sSiFgOVtqLS46OSxDWEhaZElETXE4LjQ8MFBNWFE+cGhkaipgRTQsQUtCMmhDSCcvQWFbNFUmI1leciFPOURvTjt+PgplbmRzdHJlYW0KZW5kb2JqCjYgMCBvYmoKPDwKL0YxIDcgMCBSCi9GMiA4IDAgUgo+PgplbmRvYmoKNyAwIG9iago8PAovQmFzZUZvbnQgL0hlbHZldGljYQovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZyAvTmFtZSAvRjEgL1N1YnR5cGUgL1R5cGUxIC9UeXBlIC9Gb250Cj4+CmVuZG9iago4IDAgb2JqCjw8Ci9CYXNlRm9udCAvSGVsdmV0aWNhLUJvbGQKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKL05hbWUgL0YyCi9TdWJ0eXBlIC9UeXBlMQovVHlwZSAvRm9udAo+PgplbmRvYmoKOSAwIG9iago8PAovQ29udGVudHMgMTAgMCBSCi9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdCi9SZXNvdXJjZXMgPDwKL0ZvbnQgMTEgMCBSCi9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSSBdCj4+Ci9Sb3RhdGUgMAovVHJhbnMgPDwKPj4KL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgo+PgplbmRvYmoKMTAgMCBvYmoKPDwKL0ZpbHRlciBbIC9BU0NJSTg1RGVjb2RlIC9GbGF0ZURlY29kZSBdCi9MZW5ndGggMTIxMQo+PgpzdHJlYW0KR2F0bTo+Qj9OQCY6VnMva19GU1JTUCZCai9tUk5KUSI4TilsNj43ZT8zbTpFUUE+XlM7bWpBaHFdTTVYK2Q2U1ZWJVY4KElmOHFgcUswMVYiRnAoL0RqMTxeIXVPMmRUTWwtKVRRPylbMEVYOERYLkU4OjdKNUkkVCdBMWArQ0pBSFpSZCYmVlhWUW1yVW4nXGBSb0I4XkkuS0wiQ0dATUtJPklrTGhhcGBQYkM/OmswJCEnPEZjTkAkLU8udDZNKExLL29gPmVNRGQ9a2cndCdCNW1eIUYtRkdwT2hqbyNQImFLWDxcK1pbYFMvRyIrR11KMnBhYUpWcnMiU0ZZKCNFKT5ONjwiYWtUTlI4RHFFLilAbD9LXzxGIVEuQ1MmP0ouJiJXaW9GK0FAV1EzYVFOdDVlMUAwWGJrKFQoa1ZZX2NkKWsyQHBmQD9XdSxrbmotYUNBUUVtckhTPkVJRGJALmdiXkk7KFdLVSQyKVguUDZQMjQjcD83K1ghREV0LVlObW1dRHBaZWJfbEBtUVYhJCpsWGIzaVBlWStpXiNGIm0lKVJCaCFFRFlLO21yXyohI0FJTGhZZUM+XW4/QGtDI0ZaR01eImBqO2VkI2woa0kuKCJBRGROWCg8VS0kVWV1UTNWKmU2b0NUSWBmTEZyYERJP15fbzR0WV5HbkgzXkRKc0E5ITQwV2JmXztcMkRxMXAsJl1GUi4zb0EqNV9yTCtuOW9mYygtOj9MQzkzUCNtJXFJX2cwa0RPLS84YkltOWE9U0tQJzJKY0RiZ0pJMDIuOV0iTDNcdGouXCVVTFArcDA9ZTRgPGoiM3BkM0k9dCROS1FXNkU5MTVdVm9rXkV0NGZoMCIkIitNQ2NJQkJuVUU4ISwrJUFXKGkrJT1hMFohKk9yYHI+KDgmS2VmWCc1cTNuIyE8PzNOVmZoYGFBMD9eMj8lIlxOKC9DYUhaTXFGcWdNbWtkNjd1RXNhLzU0c0BFSzQ/XTBuQjxQKnVGZnJfRy1g' +
'SldQR29jPVoqLG1rUGk+c21jMVMrQFRbU29OVnJHVlNKaU5zZCZLTnRDaUQ9VlFPJUhoZD5YbGhQakU4MFNJL0U5dTlBJSZBVkNHI2oxWlBMM0c3TSJKRkkvPDNWaj9lRSNOKiEwc0ckWiI/bld0aF43amtEPmtzL3RyOyhbbiRsIm9AUjlGYDYuTFYjcnIuYHNhOEQlXUE6S1xcKiRuYmdidVREITxKIi0oYz4qWiN1UTszSFpxQ2lCaFRbUmwtY3BNX1VHSUlhUUU1L3VlLEFjKHNTYkwrVkNHRWJJRDwqPllwakZXN1phX00odDw2JlpEUjdLRzNCcSQrJ0VXYiZJOkk/ISooQ0lLUC5kZUhQUlBUTzQiIT1iUG06L1wrQEVLK0spQkJASFZdPFwyIVtiIldFYz91R0FtNzpkVTVRVSdMPUtqPz0xNz1lNVp1OS8/SEsnVHM0S2E2PC9FPE9dOSZYLFcqJjVPLSVXPUYyOEMrRGs7TGU0MCJHZ1RDZFFYUWkxST84NE5MLUNXVD5jJDFyZl5YIkA9RXRBPSZPKmxRNzZPLz1kK0JoZFBjTVVKcGtDXEdIZi45KFlkfj4KZW5kc3RyZWFtCmVuZG9iagoxMSAwIG9iago8PAovRjEgMTIgMCBSCi9GMiAxMyAwIFIKPj4KZW5kb2JqCjEyIDAgb2JqCjw8Ci9CYXNlRm9udCAvSGVsdmV0aWNhCi9FbmNvZGluZyAvV2luQW5zaUVuY29kaW5nCi9OYW1lIC9GMQovU3VidHlwZSAvVHlwZTEKL1R5cGUgL0ZvbnQKPj4KZW5kb2JqCjEzIDAgb2JqCjw8Ci9CYXNlRm9udCAvSGVsdmV0aWNhLUJvbGQKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKL05hbWUgL0YyCi9TdWJ0eXBlIC9UeXBlMQovVHlwZSAvRm9udAo+PgplbmRvYmoKMTQgMCBvYmoKPDwKL0NvbnRlbnRzIDE1IDAgUgovTWVkaWFCb3ggWyAwIDAgNTk1LjI3NTYgODQxLjg4OTggXQovUmVzb3VyY2VzIDw8Ci9Gb250IDE2IDAgUgovUHJvY1NldCBbIC9QREYgL1RleHQgL0ltYWdlQiAvSW1hZ2VDIC9JbWFnZUkgXQo+PgovUm90YXRlIDAKL1RyYW5zIDw8Cj4+Ci9UeXBlIC9QYWdlCi9QYXJlbnQgMiAwIFIKPj4KZW5kb2JqCjE1IDAgb2JqCjw8Ci9GaWx0ZXIgWyAvQVNDSUk4NURlY29kZSAvRmxhdGVEZWNvZGUgXQovTGVuZ3RoIDEyMTIKPj4Kc3RyZWFtCkdhdG06YkF1PC8mRGQ0Nkg+c2BbLjdfVExjZzUyKCcyZllxVHM0KVcoJ0NCSTZCaWFZV3IpSXU4KkRbO2I2XnVvUV01M2E6N2pgIWUoa11Ecm06TFtPb1tbNTBSQk5bKSs3XSVWSTtlSkstN2IrVC8zLUByUzZlNGRLW0syaTQuUV0+bjo6U25GLF1tcT5lblJMZCN1aDdwJzVqIUxSOis2ZURhYUdlWCtMKSZQNG5nRydbPzd0X0hNTTMtPyEkczY1amZkYmVuUSIhUyxPS3VkOipdamVNZHRcKiNrRUcuVjNyLzNpP2tVNms1UDJcbjpOLGUnYmFVOz9HRmZnRG91byIyOENJOylbNShTJjdgL0dlOG45U0QlTzVBN2ZmLjlhPnRbYXBDZGZLV1ElMWlMQSVbXlUxaWg0U2ZZcDpsJyxiVixhPF5dcysncVs2XFgiPCowQDcyYSpcUE9eWkAoZF1jYGE1LmZmQmkrLE49XGhPWkojJkpvKkRnUixLdStEc2gmYTMmJSdlWnRBSy9IJmgxOlJEIjVfQyhAQiFMWmdhc21jWD4vJ0BmQztZPDk+X18kPCktPk90LE9RJXRcJiE3MGQtNGxiPE1XJ0xWP1RdO2IvWSFIN0FrQlNzYjxNJSNHJjM9bl5cPj50RSFlM0I/KFwkTEBkPCoqY2Y2OHM9WShMSFBeVEZgdCdCSXJ1WixeamgpbGcndTtyZiJNQEE3LWxUOG8lQzBfWGdeUUVzdTVcPGBcTU8mdWIiamw6NENXPztWXVdiSXEsMVlvbSVIQF1IUj5VWGMwPVZXbDFWQGhpSWtbVjApN3AkLjg+dWwiIj9kRDNhVWdaRF1yPFFHJGtZSFIzayosOC01OUMtPlcyNjE/cE1ockYoQixrTSMuJzEycVxyRSoxOWdIPlJkUyVeQ01MRF9TQ2BJRkxRP1deP1sjNj1nYUBqXGppWE5MM3UtJ1IuLWksOWFNSjRnQVFZZkI0P0slN1ZxKlZuLTxMKTgxU21ePT9IO3JVITFadSFdU0I1OiVPdGMkREk/UkdzKiIvSiVOXVlvZVRtXjtsJmcwZ0JLO1xga1dIJT9fPVspY2ApNztUMChWZSNCYVpxUmdDPC0/MWMwbHBVWyQ7J0JqKGtmaWFFUlRDXUJlOSNDbFBZR2AmZDJPOkEhNCZfLXFDVD9db2o8STBIVTU/b18lO2QiclY+OlBbLiQraixAaTsnKHFjZ0k3RSF1OUxvJjdsOGlQJUhHRSlyKyE0RDQyVSQ0ZS9Ob1REZzNoTnJtIllIbHAsYSJrblwjTmNONCUuSm0lbz5Zc3I5SUU7TUI7Ti1vQldQayFiW2NwKkczTyRiZC89KGorW3JDWDJpWj04aTRYMUxUcGphcjYwLUo2aVdBcnNSRj9HKFxFW21QMkU2SVZ1IzpGOCFHKk86Kl0lJ2QqWWUmVmM0YVhwcDs6YiMzZT9VT1Y/V21eT1BtRCQiWkZhSS0+SHVOYT0hRC9HQzY4c0NTYmwrNF0mYCJ1WW1XOmFgZGMsaW5nJiNIVjNubGgoRUg7bSxTMkl0Vm45PVFDXT1eOGBSNWhxcF9CKmczXm1VWUs9aC1hVDxcJil+PgplbmRzdHJlYW0KZW5kb2JqCjE2IDAgb2JqCjw8Ci9GMSAxNyAwIFIKL0YyIDE4IDAgUgo+PgplbmRvYmoKMTcgMCBvYmoKPDwKL0Jhc2VGb250IC9IZWx2ZXRpY2EKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKL05hbWUgL0YxCi9TdWJ0eXBlIC9UeXBlMQovVHlwZSAvRm9udAo+PgplbmRvYmoKMTggMCBvYmoKPDwKL0Jhc2VGb250IC9IZWx2ZXRpY2EtQm9sZAovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZwovTmFtZSAvRjIKL1N1YnR5cGUgL1R5cGUxCi9UeXBlIC9Gb250Cj4+CmVuZG9iagoxOSAwIG9iago8PAovQ29udGVudHMgMjAgMCBSCi9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdCi9SZXNvdXJjZXMgPDwKL0ZvbnQgMjEgMCBSCi9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSSBdCj4+Ci9Sb3RhdGUgMAovVHJhbnMgPDwKPj4KL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgo+PgplbmRvYmoKMjAgMCBvYmoKPDwKL0ZpbHRlciBbIC9BU0NJSTg1RGVjb2RlIC9GbGF0ZURlY29kZSBdCi9MZW5ndGggMTIxNQo+PgpzdHJlYW0KR2F0bTo+Qj9OQCY6VnMva19GU1JTUCZCVjMqYlNUJT9rZV9MbDkzTF1GW0poL0ovQTBWZVVfW3AtQzs5Nlk9aTo4Z1VALnJWR2pLb11eNiMiRmsrWDJiRitqIUs9YGpURj9EXTpnTU5uUiI2NDM8UjJPWjsqREQiVm1IWD4iQUZfaFE9XSsiJ0wiT2BeTCprck5JPkk4LU5zSDduQD02PUdiVWFaUXQ/YW8pJStsKF5BLl0oLCVLaSpZYCcvO0tLXVpeTmx1clFbJGRXOURHVmJkLG4tY0Jiak1d' +
'YEc7OjFjMFYoRic9ND4yK0IqT0RMND86LklqP0M/IXMjImAzJ10pdT1McyZqUGZLTXBFMEEiPzMwcTA2QDErcVZaL15JZi1OJWo4ckhBM2AxZURqOG5hODdXSDBTO2EmJTkjKT09TkBXVG81R1lIWWcrQVZvRiQlazIxOShuSV89USdobG8uJDJiZjFoUTBVUUVSW1MqY1RhMl9QSFpWX2wmI0toaz9JclZDaGRFImNLNFhHYzhDKnRhPjZlVCtXXkNRRiVdOCooQlpyKHNhJEZpNF1yLkMhJWFtSzJpLWMsImkqZEtkJWxEVHBIRlhSVVg6TlwvOjJQVnVBRGROWCg8VS0kVWV1UTNWKmU2b0NWMGtGNl5OQ18xREZJV0ZfQHEjaygxIXA3Z0dAL2Z1ZVNJPlguRGtcX2ArNEtfXWVpWV5YbFhnVSVKKVw8SGAxaWtfcl9FTjROJl5XYFVJSWs8ZjQqPiZYamBSaWsvO2FHTkExaHEmalIrP21NY3FIKWg5U04pdUQsUVZvTk08Q0NLJjMvXVlaUVtiTVFxI1RrZFw2ck5LZ0R0Mj5RQztIdUotT25FZUMlQjc8Y3JvYWhxTzBIKGk3XlF0aShvQW9tXj1OalpeMWkwX1dcdVk+c0g0JWlZby9fcUByOnVCMmxhR0s8cVciZkk+VCZbbVZyOScrQVIsRVk8PlwkMSREQXVkZSEmSTBwMCovUWtBI0JgU2xCRk5YKU9FZUpGZmBHR0hfUkghUypPQCo+RiwhXls7JlAiLEdZRkVoN2wjUDdMVCozMWopXjRnLkZDW3VIRWQsMGphb0InWDNLayZVL1JTJiotWm9GVGw/VyhaPE4vZWYuQF1RRis7bz8pb0heWUJkIlN1YC0sIjAialtbNlJLYlpdOXIhZm5ZcTpYcVQzZi4tJSw0OUg8TzhbYDopQm8wXUYqZ0ZGYGExZW5SLD5fRVlYOEsncSRgX0BgMyxTP2QsX20pbVlhYVhydSY+T0g2bUQ/PWA3bSM8ZDpfKjpVQVQpVU8kUyEyRERdKXFaTVVAU0JPYSomOy1KP1RAInVdVlVMLCc+LidQPWFTZ2RAO19CKjlwbmhJQ29lYEs5JCdQal5DYzNaYydJM0s4LmhcP09dMF8rRUBMRDw4aXMwJ15SczxnVyxPPWVwcldBTSZzZy0oQyhyVjFpa2NNL10+OStZVD1hPVE+aHI2Klk+Y1RHZVdFKD1SRllcU1E+JzVnNj0mVDxrcGZgKEc8U2ojNkF1YGwkMTFLTSZ1IzJDXDE5NT0iLVlTLWV1SkAsWkc+JikjOmVtWEhQPm86SH4+CmVuZHN0cmVhbQplbmRvYmoKMjEgMCBvYmoKPDwKL0YxIDIyIDAgUgovRjIgMjMgMCBSCj4+CmVuZG9iagoyMiAwIG9iago8PAovQmFzZUZvbnQgL0hlbHZldGljYQovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZwovTmFtZSAvRjEKL1N1YnR5cGUgL1R5cGUxCi9UeXBlIC9Gb250Cj4+CmVuZG9iagoyMyAwIG9iago8PAovQmFzZUZvbnQgL0hlbHZldGljYS1Cb2xkCi9FbmNvZGluZyAvV2luQW5zaUVuY29kaW5nCi9OYW1lIC9GMgovU3VidHlwZSAvVHlwZTEKL1R5cGUgL0ZvbnQKPj4KZW5kb2JqCjI0IDAgb2JqCjw8Ci9Db250ZW50cyAyNSAwIFIKL01lZGlhQm94IFsgMCAwIDU5NS4yNzU2IDg0MS44ODk4IF0KL1Jlc291cmNlcyA8PAovRm9udCAyNiAwIFIKL1Byb2NTZXQgWyAvUERGIC9UZXh0IC9JbWFnZUIgL0ltYWdlQyAvSW1hZ2VJIF0KPj4KL1JvdGF0ZSAwCi9UcmFucyA8PAo+PgovVHlwZSAvUGFnZQovUGFyZW50IDIgMCBSCj4+CmVuZG9iagoyNSAwIG9iago8PAovRmlsdGVyIFsgL0FTQ0lJODVEZWNvZGUgL0ZsYXRlRGVjb2RlIF0KL0xlbmd0aCAxMjExCj4+CnN0cmVhbQpHYXRtOjk5WilAJkFJbkJhTVQnQi1HJEgnJ11AYkNsIT84YUZja29lP1lDdSIyRkl0aGgyKSUmUnRXczNTIj0+UiQsXTdLbCdHYUAuUGlMYkkqcTQ4OiZ1W2JOI2pFRSMycD5yQnBdSVdfJGZfM0VzPlRDaz4kNG5DQi1aOUcuP0tqQHNqWlxuKl4rV21saTlNSlwxbV9pU1AycUQuKyFJKGhYdCc9TW10JCJ1VFxmcnFvZlpZdFJNRWVxYWwoKnNCLW1BXF1lTGJnTDJhVyJiNChMPUMmdW1dWmUzbDsqYCgwNHQzQTVQc2xvQEhQQ2kpbjhdI282XkQtby1SL2tTWVxoWl4yaCUiRT4hXTMyQEw7NWwvQWFVLkZZYWdLK1RmU1g7Z0ErTm1NJHQ+RkVaJS4zWmpsKSIiJTNLYV1qUEcjOT1KQS4iZTc7RlNAOV9sTiNYOCtjM0khckE1M18wS2BtJ1gtPFFnIiJUbDxaZDRnJkstV144MCxLKF8odD07OV5zNCsnREpgNidjPzBhMWgqTC5galclc01PZj85cChTRk0xWFUzaGVeKVBqLWI9bUIwL1JvXEsrRFdUPF9paDokXVViSCIkR2xQTmZBLDdURVo6REpAOipoRT1DOGBJP0M/bjxBY1taJTc1aCYiVylUT2QhKStKbkBUL2w1Qigmbl9WMVdzXEZBXGNlXUlcPHFfOltmYnMpK2BiJy0yZnAxJ1A9OUo6KCpkdEwiVFU+RkQlSV1WXGdAWDBPZSdnYSokRWlbNzgsLGcsal9AN3UyX2RfV0EpN1ohKSNhYyk8YUJfXS5xMkksWE9cQmFeSSJdQnVLR1RMNDk+bWIsb2tbVHBIPD82QilvPVdFZ3Q+Q2plXGJTWFVOZ0dwciZkNS1SLixCOTU/WCMkQHBtZEFlVTwvJyhLPEFTUmI1MChhayZWK081ImkpbVo+PXBqUCNdQzU3YydVLi1pR0JZWC9fdD1VN3FeU3Q8bmpaZSRicGcvbVRtOU4ldV1eSTdyTSNGblVaWyJoQipOMlYxMmdKSywtczUxWTIzLSopJytkWGdLQStIPCQlSGsmKlhsX0puUXQqMEFaJylZdGBiXFN1Zk5fLy5BaUtNO04/NXQ2K25hTzFCYVA7XTNFXl5GTXUxWVJOR2xOTlN0RShnQS04dGA3KGtrMmciRkhAOUZfWzJMQzZPdS5TPy0kZXFrVyNfc1M2I1FwNFJIVm5KVE1UZVxkblpBOVdcUDtJbCVLPWFbWzlrJE4mTEpzVy1QUSk/ZDs1LzYobUElLUE3bGBMbExgR3RxZz8uSD4oUTxVL11PY1VfLjldQmU3LF1SZWdaNSJjKjgia0spQ1wlYDxTNWk2RT1bJztqOVIiTDUlJW1UOTFYIzthcSduWCo+QHFHUmBEOS0+Vz9UXmklL2BhW1c5a2QoTm5nSjghZl1FPkdbNVpfY2laJi5WdFJKVC5QXmxQbUQjN0JDYTNFTVQnSG0kNjonZks1UFhKbVBTa1k7TDpAQzo7bE1BYGNKUmNmclMpRSFrUVJlXmdpWyghZzJWaVo6ZGcmcUA9LGk9Ny1jUzVAPjVpbzJATSlcR0lCSGgiR15+PgplbmRzdHJlYW0KZW5kb2JqCjI2IDAgb2JqCjw8Ci9GMSAyNyAwIFIKL0YyIDI4IDAgUgo+PgplbmRvYmoKMjcgMCBvYmoKPDwKL0Jhc2VGb250IC9IZWx2ZXRpY2EKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKL05hbWUgL0YxCi9TdWJ0eXBlIC9UeXBlMQovVHlwZSAvRm9udAo+PgplbmRvYmoKMjggMCBvYmoKPDwKL0Jhc2VGb250IC9IZWx2ZXRpY2EtQm9sZAovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGlu' +
'ZwovTmFtZSAvRjIKL1N1YnR5cGUgL1R5cGUxCi9UeXBlIC9Gb250Cj4+CmVuZG9iagoyOSAwIG9iago8PAovQ29udGVudHMgMzAgMCBSCi9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdCi9SZXNvdXJjZXMgPDwKL0ZvbnQgMzEgMCBSCi9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSSBdCj4+Ci9Sb3RhdGUgMAovVHJhbnMgPDwKPj4KL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgo+PgplbmRvYmoKMzAgMCBvYmoKPDwKL0ZpbHRlciBbIC9BU0NJSTg1RGVjb2RlIC9GbGF0ZURlY29kZSBdCi9MZW5ndGggMTIwMQo+PgpzdHJlYW0KR2F0bTo5NWlmXCZBST0vZTZya0xVVnVmQmNhYydvQTZCTDBpOGcsXEBpRkQ/YGxMJ01kZjAqQnA5VTVKUENRXDI2SFVwcHFXZEQzV2hNY0pMSzhvYiddOzAuZC9zUXArUFsjVSUyNlNyIlE8KUpTLHAkdGtBTDxhMj80S25hNXInQUhNQjdMNUEqZE4yW0ZuInBxP1BjX0BpVUpAInBmUUA0TW9McT08dHJebzY1Rk5vPGVxLCkiPCk2SSdRZ1lfayc+PE9zYjNgTHFsLUFWWU9vcCpwblRtaFtbSzpTb2VvYWc0M2E4SD1oTmInc2hraFcnKzJSa1RQP1E2JktqYXQ3ZG1QTl4mYDEvUTFhX2NyJHNVaTFNXyxASDJYPTQiOVo5MWBFKjc0byhISjEtJVtbIzdnPTE9dWxiNzx1NlIuO1ViMS0yZGxlPzsuISVRNixMRVRQcUcqPmBeOiRuXUZSdD50aU1MRlhZKnNgI0c4MDNlMV5sRClRTyhpXHN0WG1VPXAyMFZVUzdCJzNRSU5wPXVaXW45ZzAlXiJFPmtXLFUwb209aTxsNis+LSYkQzlLIT4hZjU0Tz80XmN1TDVkZmM2WXRlRXFpK0FEZE1NMCQ8Mm1VZkRpN1YqZThFKTgkIUQ2Xk5DLzNfREMpKnU+SkBCIy8hWVBHdTxHP1dZIj9gT1ZybU5oXnRcPCleT1pgXVxXOy8vWl4yaXJxT0tBJiVrUTM9RnUtOUEpbmFMbyQyOzUkWSJSJEdtWj45XDIyTF4qRGM/SnVOXT5ZdEtzMF5KWmomYWVXIyVBJUFbMkdTL1Q0WFNCMDtTO2liKV9nN15IK2ZyU0g1T2ZuYTpTKFllSGxRQ2RRQTMhKzgrRnFbcGZvOVhCKU9pZyVpLzVjJHVFR2NWUGlxR0VhI1VyVmZYUUxycWQvQGYzUEdaXUFwLGc+VCZYbEI0MmczWjlBPSIuWj5KaEtrMmFNZShTViRbNzkrM1xfOC1xLjk1Km45PTMjY18hK2ZkSGU6YVJHZ1tvKWBlNmVSRG0wL1VFQzRXT0ZlTUZEb1oyZTpbJS1GcjNtVUdzMEttI3FZblhhTWJBOiwlZjNEKS1GdGBWTSUxVjpwSkdTUVwxYkFsQ0VQRHVhMEUqSUwlZlolPG5FYVpwKzwqakcsLHRmRVQ/XW4/QVRFU1w1P29QcDtjL0U/PjojPSkkK2otI2o4I0N0NU1cMl4jOmUvMy9yQnEvMyhZPmMyUm5NZmdFXTdxPjwlbmk1NUB0VSpzSHUyZmZqYCpFalRvSiI2R1VkO21yUCdcWS5yJW5zMDpcViYxZDUnOFwoY0QzS1YtRElBc3FCZDxmPjdjQDxOYEBdIyJIVV0sM24sWmJLPzlqKV07Z3VnO2tdZCstYiNyUGxeYiokcioxV2RwZmk9J0ZrWjFWQl9zMjkrcD9fYVA1WnU5Lz9ISydUczQnSTI7TWZAKXApdVlrVyolbzIvK0tpVFs8TW5ibEwqKFgvQGY+NWxvaVJsOm5QJVE0TU9MMS5IKW9KVjhkUjIjdC5DY2FZIyU0WkpRZ2JWKkJeYj9hKmU3WlciOmZcRzY7WyRoJmx+PgplbmRzdHJlYW0KZW5kb2JqCjMxIDAgb2JqCjw8Ci9GMSAzMiAwIFIKL0YyIDMzIDAgUgo+PgplbmRvYmoKMzIgMCBvYmoKPDwKL0Jhc2VGb250IC9IZWx2ZXRpY2EKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKL05hbWUgL0YxCi9TdWJ0eXBlIC9UeXBlMQovVHlwZSAvRm9udAo+PgplbmRvYmoKMzMgMCBvYmoKPDwKL0Jhc2VGb250IC9IZWx2ZXRpY2EtQm9sZAovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZwovTmFtZSAvRjIKL1N1YnR5cGUgL1R5cGUxCi9UeXBlIC9Gb250Cj4+CmVuZG9iagp4cmVmCjAgMzQKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDAwNTQgMDAwMDAgbiAKMDAwMDAwMDE0NyAwMDAwMCBuIAowMDAwMDAwMTk2IDAwMDAwIG4gCjAwMDAwMDAzOTUgMDAwMDAgbiAKMDAwMDAwMTcwMiAwMDAwMCBuIAowMDAwMDAxNzQzIDAwMDAwIG4gCjAwMDAwMDE4NTAgMDAwMDAgbiAKMDAwMDAxOTYyIDAwMDAwIG4gCjAwMDAwMDIxNjMgMDAwMDAgbiAKMDAwMDAwMzQ2NyAwMDAwMCBuIAowMDAwMDAzNTExIDAwMDAwIG4gCjAwMDAwMDM2MTkgMDAwMDAgbiAKMDAwMDAwMzczMiAwMDAwMCBuIAowMDAwMDAzOTM0IDAwMDAwIG4gCjAwMDAwMDUyMzkgMDAwMDAgbiAKMDAwMDAwNTI4MyAwMDAwMCBuIAowMDAwMDA1MzkxIDAwMDAwIG4gCjAwMDAwMDU1MDQgMDAwMDAgbiAKMDAwMDAwNTcwNiAwMDAwMCBuIAowMDAwMDA3MDE0IDAwMDAwIG4gCjAwMDAwMDcwNTggMDAwMDAgbiAKMDAwMDAwNzE2NiAwMDAwMCBuIAowMDAwMDA3Mjc5IDAwMDAwIG4gCjAwMDAwMDc0ODEgMDAwMDAgbiAKMDAwMDAwODc4NSAwMDAwMCBuIAowMDAwMDA4ODI5IDAwMDAwIG4gCjAwMDAwMDg5MzcgMDAwMDAgbiAKMDAwMDAwOTA1MCAwMDAwMCBuIAowMDAwMDA5MjUyIDAwMDAwIG4gCjAwMDAwMTA1NDYgMDAwMDAgbiAKMDAwMDAxMDU5MCAwMDAwMCBuIAowMDAwMDEwNjk4IDAwMDAwIG4gCnRyYWlsZXIKPDwKL1NpemUgMzQKL1Jvb3QgMyAwIFIKL0luZm8gMSAwIFIKPj4Kc3RhcnR4cmVmCjEwODExCiUlRU9GCg==';

const seeds = [
  { name: 'LEONEL DE SOUZA SANTOS', cpf: '02960408519', cnpj: '14464586000150', vehicle: 'CHEVROLET MONTANA LS2', plate: 'FCM1081' },
  { name: 'DIEGO MARTINS SILVA SANTOS', cpf: '53844759867', cnpj: '14464586000150', vehicle: 'FIAT STRADA', plate: 'TLK4H52' },
  { name: 'LEANDRO MARTINS DE OLIVEIRA', cpf: '22146424800', cnpj: '21967711000100', vehicle: 'FIAT STRADA ENDURANCE', plate: 'STT6J03' },
  { name: 'NACIEL SANTOS DA SILVA', cpf: '45217307870', cnpj: '14464586000150', vehicle: 'CHEVROLET MONTANA', plate: 'GEK6828' },
  { name: 'TIAGO MOREIRA DA SILVA FERREIRA', cpf: '10315762586', cnpj: '14464586000150', vehicle: 'FIAT STRADA', plate: 'TMC7G68' },
  { name: 'TIAGO TOLEDO DIAS', cpf: '32348689804', cnpj: '21967711000100', vehicle: 'FIAT STRADA ENDURANCE', plate: 'SUI1F53' },
];

const digits = (value: unknown) => String(value || '').replace(/\D/g, '');
const hash = (bytes: Uint8Array | Buffer) => createHash('sha256').update(bytes).digest('hex');

export default async function handler(req: any, res?: any) {
  if ((req?.method || 'GET') !== 'GET') return sendJson(res, { ok: false, error: 'method_not_allowed' }, 405);
  if (String(req?.query?.token || '') !== SEED_TOKEN) return sendJson(res, { ok: false, error: 'forbidden' }, 403);
  try {
    const service = getServiceClient();
    const [companiesResult, employeesResult] = await Promise.all([
      service.from('empresas').select('id,nome,cnpj'),
      service.from('funcionarios').select('id,nome,cpf,company_id,empresa_id'),
    ]);
    if (companiesResult.error) throw companiesResult.error;
    if (employeesResult.error) throw employeesResult.error;

    const sourceBytes = Buffer.from(PDF_BASE64, 'base64');
    const sourceHash = hash(sourceBytes);
    const pdf = await PDFDocument.load(sourceBytes, { ignoreEncryption: true });
    if (pdf.getPageCount() !== seeds.length) throw new Error(`PDF possui ${pdf.getPageCount()} páginas; esperado ${seeds.length}.`);

    const results: any[] = [];
    for (let index = 0; index < seeds.length; index += 1) {
      const seed = seeds[index];
      const company = (companiesResult.data || []).find((row: any) => digits(row.cnpj) === seed.cnpj);
      if (!company) { results.push({ name: seed.name, status: 'EMPRESA_NAO_LOCALIZADA' }); continue; }
      const employee = (employeesResult.data || []).find((row: any) => digits(row.cpf) === seed.cpf && (row.company_id === company.id || row.empresa_id === company.id));
      if (!employee) { results.push({ name: seed.name, status: 'FUNCIONARIO_NAO_LOCALIZADO' }); continue; }

      const { data: existing, error: existingError } = await service.from('payroll_documents')
        .select('id,storage_path')
        .eq('employee_id', employee.id)
        .eq('competencia', COMPETENCIA)
        .eq('document_type', 'RECIBO_GARAGEM')
        .eq('is_current', true)
        .maybeSingle();
      if (existingError) throw existingError;
      if (existing) { results.push({ name: seed.name, status: 'JA_EXISTE', id: existing.id }); continue; }

      const output = await PDFDocument.create();
      const [copied] = await output.copyPages(pdf, [index]);
      output.addPage(copied);
      const pageBytes = new Uint8Array(await output.save({ addDefaultPage: false, useObjectStreams: false }));
      const pageHash = hash(pageBytes);
      const filename = `Recibo_Garagem_09-2026_${seed.name.replace(/\s+/g, '_')}.pdf`;
      const storagePath = `${company.id}/${COMPETENCIA}/garagem/${employee.id}/recibo-garagem-202609.pdf`;
      const { error: storageError } = await service.storage.from(BUCKET).upload(storagePath, Buffer.from(pageBytes), { contentType: 'application/pdf', upsert: true });
      if (storageError) throw storageError;

      const now = new Date().toISOString();
      const { data: document, error: documentError } = await service.from('payroll_documents').insert({
        company_id: company.id,
        employee_id: employee.id,
        competencia: COMPETENCIA,
        document_type: 'RECIBO_GARAGEM',
        storage_bucket: BUCKET,
        storage_path: storagePath,
        original_filename: filename,
        mime_type: 'application/pdf',
        file_size: pageBytes.byteLength,
        document_sha256: pageHash,
        source_sha256: sourceHash,
        source_page_start: index + 1,
        source_page_end: index + 1,
        document_version: 1,
        is_current: true,
        net_amount: 200,
        extracted_data: {
          origem: 'RECIBOS_GARAGEM_09_2026_USUARIO',
          nome: seed.name,
          cpf: seed.cpf,
          veiculo: seed.vehicle,
          placa: seed.plate,
          valor_garagem: 200,
          referencia_assinatura_dia: 5,
          nao_bloqueante: true,
          pode_anexar_depois: true,
        },
        match_confidence: 100,
        status: 'AGUARDANDO_ASSINATURA',
        confirmed: true,
        confirmed_at: now,
        payment_kind: 'ORIGINAL',
        payment_sequence: 1,
        entitlement_amount: 200,
        prior_paid_amount: 0,
        payment_reason: 'Custeio de garagem',
        payment_state: 'PAGO',
      }).select('id').single();
      if (documentError) throw documentError;
      results.push({ name: seed.name, status: 'IMPORTADO', id: document.id });
    }

    return sendJson(res, { ok: true, competencia: COMPETENCIA, results });
  } catch (error: any) {
    console.error('[seed-garagem-202609]', error);
    return sendJson(res, { ok: false, error: String(error?.message || error) }, 500);
  }
}
