name: Liberar campos do pre-cadastro

on:
  push:
    paths:
      - '.github/trigger-liberar-campos.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Liberar todos os campos manuais
       