name: Preencher automaticamente dados da rescisao

on:
  push:
    paths:
      - '.github/workflows/patch-rescisao-auto-summary.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.G